[versions]
dokka = "1.9.20"
spek = "2.0.19"
unbrokenDome = "0.5.0"
okhttp = "4.12.0"
jackson = "2.17.2"
# No need to keep the same Kotlin version with Gradle, at least because kotlin runtime is a transitive dependency of okhttp
kotlin = "1.9.23"
junit = "5.10.3"

[libraries]
snakeyaml = "org.yaml:snakeyaml:2.2"
assertk = "com.willowtreeapps.assertk:assertk-jvm:0.28.1"
# version 1.13.8 doesn't work because of JVM 11 bytecode despite of https://github.com/mockk/mockk/pull/1161
mockk = "io.mockk:mockk:1.13.11"
tabbedCodeExtension = "com.bmuschko:asciidoctorj-tabbed-code-extension:0.3"
orgJson = "org.json:json:20240303"
jsonPath = "com.jayway.jsonpath:json-path:2.9.0"
kotestAssertions = "io.kotest:kotest-assertions-core:5.9.1"
jacksonDataBind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jacksonDataFormatYaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okHttpTls = { module = "com.squareup.okhttp3:okhttp-tls", version.ref = "okhttp" }
okHttpMockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
unbrokenDomePluginUtils = { module = "org.unbroken-dome.gradle-plugin-utils:gradle-plugin-utils", version.ref = "unbrokenDome" }
unbrokenDomeTestUtils = { module = "org.unbroken-dome.gradle-plugin-utils:gradle-plugin-test-utils", version.ref = "unbrokenDome" }
spekDsl = { module = "org.spekframework.spek2:spek-dsl-jvm", version.ref = "spek" }
spekRunner = { module = "org.spekframework.spek2:spek-runner-junit5", version.ref = "spek" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.8.1" }


[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.6" }
gradlePublish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
asciidoctor = { id = "org.asciidoctor.jvm.convert", version = "4.0.2" }
benManesVersions = { id = "com.github.ben-manes.versions", version = "0.51.0" }
binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.15.1" }

[bundles]
defaultTests = ["junit", "kotestAssertions"]
